"use client"

import { useState, useEffect, useMemo } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"
import { X, Search, Loader2 } from "lucide-react"
import Image from "next/image"

interface PokemonSearchProps {
  onSelectPokemon: (pokemon: any) => void
  onClose: () => void
}

export function PokemonSearch({ onSelectPokemon, onClose }: PokemonSearchProps) {
  const [searchTerm, setSearchTerm] = useState("")
  const [allPokemon, setAllPokemon] = useState<any[]>([])
  const [loading, setLoading] = useState(true)
  const [searchResults, setSearchResults] = useState<any[]>([])

  // Comprehensive list of Pokemon names for better search coverage
  const pokemonDatabase = useMemo(
    () => [
      // Gen 1
      "bulbasaur",
      "ivysaur",
      "venusaur",
      "charmander",
      "charmeleon",
      "charizard",
      "squirtle",
      "wartortle",
      "blastoise",
      "caterpie",
      "metapod",
      "butterfree",
      "weedle",
      "kakuna",
      "beedrill",
      "pidgey",
      "pidgeotto",
      "pidgeot",
      "rattata",
      "raticate",
      "spearow",
      "fearow",
      "ekans",
      "arbok",
      "pikachu",
      "raichu",
      "sandshrew",
      "sandslash",
      "nidoran-f",
      "nidorina",
      "nidoqueen",
      "nidoran-m",
      "nidorino",
      "nidoking",
      "clefairy",
      "clefable",
      "vulpix",
      "ninetales",
      "jigglypuff",
      "wigglytuff",
      "zubat",
      "golbat",
      "oddish",
      "gloom",
      "vileplume",
      "paras",
      "parasect",
      "venonat",
      "venomoth",
      "diglett",
      "dugtrio",
      "meowth",
      "persian",
      "psyduck",
      "golduck",
      "mankey",
      "primeape",
      "growlithe",
      "arcanine",
      "poliwag",
      "poliwhirl",
      "poliwrath",
      "abra",
      "kadabra",
      "alakazam",
      "machop",
      "machoke",
      "machamp",
      "bellsprout",
      "weepinbell",
      "victreebel",
      "tentacool",
      "tentacruel",
      "geodude",
      "graveler",
      "golem",
      "ponyta",
      "rapidash",
      "slowpoke",
      "slowbro",
      "magnemite",
      "magneton",
      "farfetchd",
      "doduo",
      "dodrio",
      "seel",
      "dewgong",
      "grimer",
      "muk",
      "shellder",
      "cloyster",
      "gastly",
      "haunter",
      "gengar",
      "onix",
      "drowzee",
      "hypno",
      "krabby",
      "kingler",
      "voltorb",
      "electrode",
      "exeggcute",
      "exeggutor",
      "cubone",
      "marowak",
      "hitmonlee",
      "hitmonchan",
      "lickitung",
      "koffing",
      "weezing",
      "rhyhorn",
      "rhydon",
      "chansey",
      "tangela",
      "kangaskhan",
      "horsea",
      "seadra",
      "goldeen",
      "seaking",
      "staryu",
      "starmie",
      "mr-mime",
      "scyther",
      "jynx",
      "electabuzz",
      "magmar",
      "pinsir",
      "tauros",
      "magikarp",
      "gyarados",
      "lapras",
      "ditto",
      "eevee",
      "vaporeon",
      "jolteon",
      "flareon",
      "porygon",
      "omanyte",
      "omastar",
      "kabuto",
      "kabutops",
      "aerodactyl",
      "snorlax",
      "articuno",
      "zapdos",
      "moltres",
      "dratini",
      "dragonair",
      "dragonite",
      "mewtwo",
      "mew",
      "venusaur-mega",
      "charizard-mega-x",
      "charizard-mega-y",
      "blastoise-mega",
      "beedrill-mega",
      "pidgeot-mega",
      "alakazam-mega",
      "slowbro-mega",
      "gengar-mega",
      "kangaskhan-mega",
      "pinsir-mega",
      "gyarados-mega",
      "aerodactyl-mega",
      "mewtwo-mega-x",
      "mewtwo-mega-y",
      "rattata-alola",
      "raticate-alola",
      "raichu-alola",
      "sandshrew-alola",
      "sandslash-alola",
      "vulpix-alola",
      "ninetales-alola",
      "diglett-alola",
      "dugtrio-alola",
      "meowth-alola",
      "meowth-galar",
      "persian-alola",
      "geodude-alola",
      "graveler-alola",
      "golem-alola",
      "ponyta-galar",
      "rapidash-galar",
      "slowpoke-galar",
      "slowbro-galar",
      "farfetchd-galar",
      "weezing-galar",
      "mr-mime-galar",
      "articuno-galar",
      "zapdos-galar",
      "moltres-galar",
      "grimer-alola",
      "muk-alola",
      "exeggutor-alola",
      "marowak-alola",
      "voltorb-hisui",
      "electrode-hisui",
      "growlithe-hisui",
      "arcanine-hisui",

      // Gen 2
      "chikorita",
      "bayleef",
      "meganium",
      "cyndaquil",
      "quilava",
      "typhlosion",
      "totodile",
      "croconaw",
      "feraligatr",
      "sentret",
      "furret",
      "hoothoot",
      "noctowl",
      "ledyba",
      "ledian",
      "spinarak",
      "ariados",
      "crobat",
      "chinchou",
      "lanturn",
      "pichu",
      "cleffa",
      "igglybuff",
      "togepi",
      "togetic",
      "natu",
      "xatu",
      "mareep",
      "flaaffy",
      "ampharos",
      "bellossom",
      "marill",
      "azumarill",
      "sudowoodo",
      "politoed",
      "hoppip",
      "skiploom",
      "jumpluff",
      "aipom",
      "sunkern",
      "sunflora",
      "yanma",
      "wooper",
      "quagsire",
      "espeon",
      "umbreon",
      "murkrow",
      "slowking",
      "misdreavus",
      "unown",
      "wobbuffet",
      "girafarig",
      "pineco",
      "forretress",
      "dunsparce",
      "gligar",
      "steelix",
      "snubbull",
      "granbull",
      "qwilfish",
      "scizor",
      "shuckle",
      "heracross",
      "sneasel",
      "teddiursa",
      "ursaring",
      "slugma",
      "magcargo",
      "swinub",
      "piloswine",
      "corsola",
      "remoraid",
      "octillery",
      "delibird",
      "mantine",
      "skarmory",
      "houndour",
      "houndoom",
      "kingdra",
      "phanpy",
      "donphan",
      "porygon2",
      "stantler",
      "smeargle",
      "tyrogue",
      "hitmontop",
      "smoochum",
      "elekid",
      "magby",
      "miltank",
      "blissey",
      "raikou",
      "entei",
      "suicune",
      "larvitar",
      "pupitar",
      "tyranitar",
      "lugia",
      "ho-oh",
      "celebi",
      "ampharos-mega",
      "steelix-mega",
      "scizor-mega",
      "heracross-mega",
      "houndoom-mega",
      "tyranitar-mega",
      "slowking-galar",
      "corsola-galar",
      "typhlosion-hisui",

      // Gen 3
      "treecko",
      "grovyle",
      "sceptile",
      "torchic",
      "combusken",
      "blaziken",
      "mudkip",
      "marshtomp",
      "swampert",
      "poochyena",
      "mightyena",
      "zigzagoon",
      "linoone",
      "wurmple",
      "silcoon",
      "beautifly",
      "cascoon",
      "dustox",
      "lotad",
      "lombre",
      "ludicolo",
      "seedot",
      "nuzleaf",
      "shiftry",
      "taillow",
      "swellow",
      "wingull",
      "pelipper",
      "ralts",
      "kirlia",
      "gardevoir",
      "surskit",
      "masquerain",
      "shroomish",
      "breloom",
      "slakoth",
      "vigoroth",
      "slaking",
      "nincada",
      "ninjask",
      "shedinja",
      "whismur",
      "loudred",
      "exploud",
      "makuhita",
      "hariyama",
      "azurill",
      "nosepass",
      "skitty",
      "delcatty",
      "sableye",
      "mawile",
      "aron",
      "lairon",
      "aggron",
      "meditite",
      "medicham",
      "electrike",
      "manectric",
      "plusle",
      "minun",
      "volbeat",
      "illumise",
      "roselia",
      "gulpin",
      "swalot",
      "carvanha",
      "sharpedo",
      "wailmer",
      "wailord",
      "numel",
      "camerupt",
      "torkoal",
      "spoink",
      "grumpig",
      "spinda",
      "trapinch",
      "vibrava",
      "flygon",
      "cacnea",
      "cacturne",
      "swablu",
      "altaria",
      "zangoose",
      "seviper",
      "lunatone",
      "solrock",
      "barboach",
      "whiscash",
      "corphish",
      "crawdaunt",
      "baltoy",
      "claydol",
      "lileep",
      "cradily",
      "anorith",
      "armaldo",
      "feebas",
      "milotic",
      "castform",
      "kecleon",
      "shuppet",
      "banette",
      "duskull",
      "dusclops",
      "tropius",
      "chimecho",
      "absol",
      "wynaut",
      "snorunt",
      "glalie",
      "spheal",
      "sealeo",
      "walrein",
      "clamperl",
      "huntail",
      "gorebyss",
      "relicanth",
      "luvdisc",
      "bagon",
      "shelgon",
      "salamence",
      "beldum",
      "metang",
      "metagross",
      "regirock",
      "regice",
      "registeel",
      "latias",
      "latios",
      "kyogre",
      "groudon",
      "rayquaza",
      "jirachi",
      "deoxys",
      "sceptile-mega",
      "blaziken-mega",
      "swampert-mega",
      "gardevoir-mega",
      "sableye-mega",
      "mawile-mega",
      "aggron-mega",
      "medicham-mega",
      "manectric-mega",
      "sharpedo-mega",
      "camerupt-mega",
      "altaria-mega",
      "banette-mega",
      "absol-mega",
      "glalie-mega",
      "salamence-mega",
      "metagross-mega",
      "latias-mega",
      "latios-mega",
      "kyogre-primal",
      "groudon-primal",
      "rayquaza-mega",

      // Gen 4
      "turtwig",
      "grotle",
      "torterra",
      "chimchar",
      "monferno",
      "infernape",
      "piplup",
      "prinplup",
      "empoleon",
      "starly",
      "staravia",
      "staraptor",
      "bidoof",
      "bibarel",
      "kricketot",
      "kricketune",
      "shinx",
      "luxio",
      "luxray",
      "budew",
      "roserade",
      "cranidos",
      "rampardos",
      "shieldon",
      "bastiodon",
      "burmy",
      "wormadam",
      "mothim",
      "combee",
      "vespiquen",
      "pachirisu",
      "buizel",
      "floatzel",
      "cherubi",
      "cherrim",
      "shellos",
      "gastrodon",
      "ambipom",
      "drifloon",
      "drifblim",
      "buneary",
      "lopunny",
      "mismagius",
      "honchkrow",
      "glameow",
      "purugly",
      "chingling",
      "stunky",
      "skuntank",
      "bronzor",
      "bronzong",
      "bonsly",
      "mime-jr",
      "happiny",
      "chatot",
      "spiritomb",
      "gible",
      "gabite",
      "garchomp",
      "munchlax",
      "riolu",
      "lucario",
      "hippopotas",
      "hippowdon",
      "skorupi",
      "drapion",
      "croagunk",
      "toxicroak",
      "carnivine",
      "finneon",
      "lumineon",
      "mantyke",
      "snover",
      "abomasnow",
      "weavile",
      "magnezone",
      "lickilicky",
      "rhyperior",
      "tangrowth",
      "electivire",
      "magmortar",
      "togekiss",
      "yanmega",
      "leafeon",
      "glaceon",
      "gliscor",
      "mamoswine",
      "porygon-z",
      "gallade",
      "probopass",
      "dusknoir",
      "froslass",
      "rotom",
      "uxie",
      "mesprit",
      "azelf",
      "dialga",
      "palkia",
      "heatran",
      "regigigas",
      "giratina",
      "cresselia",
      "phione",
      "manaphy",
      "darkrai",
      "shaymin",
      "arceus",
      "lopunny-mega",
      "garchomp-mega",
      "lucario-mega",
      "abomasnow-mega",
      "gallade-mega",
      "dialga-origin",
      "palkia-origin",
      "giratina-origin",
      "shaymin-sky",
      "rotom-heat",
      "rotom-wash",
      "rotom-frost",
      "rotom-fan",
      "rotom-mow",

      // Gen 5
      "victini",
      "snivy",
      "servine",
      "serperior",
      "tepig",
      "pignite",
      "emboar",
      "oshawott",
      "dewott",
      "samurott",
      "patrat",
      "watchog",
      "lillipup",
      "herdier",
      "stoutland",
      "purrloin",
      "liepard",
      "pansage",
      "simisage",
      "pansear",
      "simisear",
      "panpour",
      "simipour",
      "munna",
      "musharna",
      "pidove",
      "tranquill",
      "unfezant",
      "blitzle",
      "zebstrika",
      "roggenrola",
      "boldore",
      "gigalith",
      "woobat",
      "swoobat",
      "drilbur",
      "excadrill",
      "audino",
      "timburr",
      "gurdurr",
      "conkeldurr",
      "tympole",
      "palpitoad",
      "seismitoad",
      "throh",
      "sawk",
      "sewaddle",
      "swadloon",
      "leavanny",
      "venipede",
      "whirlipede",
      "scolipede",
      "cottonee",
      "whimsicott",
      "petilil",
      "lilligant",
      "basculin",
      "sandile",
      "krokorok",
      "krookodile",
      "darumaka",
      "darmanitan",
      "maractus",
      "dwebble",
      "crustle",
      "scraggy",
      "scrafty",
      "sigilyph",
      "yamask",
      "cofagrigus",
      "tirtouga",
      "carracosta",
      "archen",
      "archeops",
      "trubbish",
      "garbodor",
      "zorua",
      "zoroark",
      "minccino",
      "cinccino",
      "gothita",
      "gothorita",
      "gothitelle",
      "solosis",
      "duosion",
      "reuniclus",
      "ducklett",
      "swanna",
      "vanillite",
      "vanillish",
      "vanilluxe",
      "deerling",
      "sawsbuck",
      "emolga",
      "karrablast",
      "escavalier",
      "foongus",
      "amoonguss",
      "frillish",
      "jellicent",
      "alomomola",
      "joltik",
      "galvantula",
      "ferroseed",
      "ferrothorn",
      "klink",
      "klang",
      "klinklang",
      "tynamo",
      "eelektrik",
      "eelektross",
      "elgyem",
      "beheeyem",
      "litwick",
      "lampent",
      "chandelure",
      "axew",
      "fraxure",
      "haxorus",
      "cubchoo",
      "beartic",
      "cryogonal",
      "shelmet",
      "accelgor",
      "stunfisk",
      "mienfoo",
      "mienshao",
      "druddigon",
      "golett",
      "golurk",
      "pawniard",
      "bisharp",
      "bouffalant",
      "rufflet",
      "braviary",
      "vullaby",
      "mandibuzz",
      "heatmor",
      "durant",
      "deino",
      "zweilous",
      "hydreigon",
      "larvesta",
      "volcarona",
      "cobalion",
      "terrakion",
      "virizion",
      "tornadus",
      "thundurus",
      "reshiram",
      "zekrom",
      "landorus",
      "kyurem",
      "keldeo",
      "meloetta",
      "genesect",
      "audino-mega",
      "samurott-hisui",
      "lilligant-hisui",
      "zorua-hisui",
      "zoroark-hisui",
      "braviary-hisui",
      "basculin-white-striped",
      "darumaka-galar",
      "darmanitan-galar",
      "yamask-galar",
      "stunfisk-galar",
      "tornadus-therian",
      "thundurus-therian",
      "landorus-therian",
      "kyurem-black",
      "kyurem-white",

      // Gen 6
      "chespin",
      "quilladin",
      "chesnaught",
      "fennekin",
      "braixen",
      "delphox",
      "froakie",
      "frogadier",
      "greninja",
      "bunnelby",
      "diggersby",
      "fletchling",
      "fletchinder",
      "talonflame",
      "scatterbug",
      "spewpa",
      "vivillon",
      "litleo",
      "pyroar",
      "flabebe",
      "floette",
      "florges",
      "skiddo",
      "gogoat",
      "pancham",
      "pangoro",
      "furfrou",
      "espurr",
      "meowstic",
      "honedge",
      "doublade",
      "aegislash",
      "spritzee",
      "aromatisse",
      "swirlix",
      "slurpuff",
      "inkay",
      "malamar",
      "binacle",
      "barbaracle",
      "skrelp",
      "dragalge",
      "clauncher",
      "clawitzer",
      "helioptile",
      "heliolisk",
      "tyrunt",
      "tyrantrum",
      "amaura",
      "aurorus",
      "sylveon",
      "hawlucha",
      "dedenne",
      "carbink",
      "goomy",
      "sliggoo",
      "goodra",
      "klefki",
      "phantump",
      "trevenant",
      "pumpkaboo",
      "gourgeist",
      "bergmite",
      "avalugg",
      "noibat",
      "noivern",
      "xerneas",
      "yveltal",
      "zygarde",
      "diancie",
      "hoopa",
      "volcanion",
      "greninja-ash",
      "floette-eternal",
      "aegislash-blade",
      "sliggoo-hisui",
      "goodra-hisui",
      "avalugg-hisui",
      "diancie-mega",
      "hoopa-unbound",
      "zygarde-10",
      "zygarde-complete",

      // Gen 7
      "rowlet",
      "dartrix",
      "decidueye",
      "litten",
      "torracat",
      "incineroar",
      "popplio",
      "brionne",
      "primarina",
      "pikipek",
      "trumbeak",
      "toucannon",
      "yungoos",
      "gumshoos",
      "grubbin",
      "charjabug",
      "vikavolt",
      "crabrawler",
      "crabominable",
      "oricorio",
      "cutiefly",
      "ribombee",
      "rockruff",
      "lycanroc",
      "wishiwashi",
      "mareanie",
      "toxapex",
      "mudbray",
      "mudsdale",
      "dewpider",
      "araquanid",
      "fomantis",
      "lurantis",
      "morelull",
      "shiinotic",
      "salandit",
      "salazzle",
      "stufful",
      "bewear",
      "bounsweet",
      "steenee",
      "tsareena",
      "comfey",
      "oranguru",
      "passimian",
      "wimpod",
      "golisopod",
      "sandygast",
      "palossand",
      "pyukumuku",
      "type-null",
      "silvally",
      "minior",
      "komala",
      "turtonator",
      "togedemaru",
      "mimikyu",
      "bruxish",
      "drampa",
      "dhelmise",
      "jangmo-o",
      "hakamo-o",
      "kommo-o",
      "tapu-koko",
      "tapu-lele",
      "tapu-bulu",
      "tapu-fini",
      "cosmog",
      "cosmoem",
      "solgaleo",
      "lunala",
      "necrozma",
      "magearna",
      "marshadow",
      "poipole",
      "naganadel",
      "stakataka",
      "blacephalon",
      "zeraora",
      "decidueye-hisui",
      "oricorio-pom-pom",
      "oricorio-pau",
      "oricorio-sensu",
      "lycanroc-midday",
      "lycanroc-midnight",
      "lycanroc-dusk",
      "wishiwashi-school",
      "minior-meteor",
      "mimikyu-busted",
      "necrozma-dusk",
      "necrozma-dawn",
      "necrozma-ultra",
      "magearna-original",

      // Gen 8
      "grookey",
      "thwackey",
      "rillaboom",
      "scorbunny",
      "raboot",
      "cinderace",
      "sobble",
      "drizzile",
      "inteleon",
      "skwovet",
      "greedent",
      "rookidee",
      "corvisquire",
      "corviknight",
      "blipbug",
      "dottler",
      "orbeetle",
      "nickit",
      "thievul",
      "gossifleur",
      "eldegoss",
      "wooloo",
      "dubwool",
      "chewtle",
      "drednaw",
      "yamper",
      "boltund",
      "rolycoly",
      "carkol",
      "coalossal",
      "applin",
      "flapple",
      "appletun",
      "silicobra",
      "sandaconda",
      "cramorant",
      "arrokuda",
      "barraskewda",
      "toxel",
      "toxtricity",
      "sizzlipede",
      "centiskorch",
      "clobbopus",
      "grapploct",
      "sinistea",
      "polteageist",
      "hatenna",
      "hattrem",
      "hatterene",
      "impidimp",
      "morgrem",
      "grimmsnarl",
      "obstagoon",
      "perrserker",
      "cursola",
      "sirfetchd",
      "mr-rime",
      "runerigus",
      "milcery",
      "alcremie",
      "falinks",
      "pincurchin",
      "snom",
      "frosmoth",
      "stonjourner",
      "eiscue",
      "indeedee",
      "morpeko",
      "cufant",
      "copperajah",
      "dracozolt",
      "arctozolt",
      "dracovish",
      "arctovish",
      "duraludon",
      "dreepy",
      "drakloak",
      "dragapult",
      "zacian",
      "zamazenta",
      "eternatus",
      "kubfu",
      "urshifu",
      "regieleki",
      "regidrago",
      "glastrier",
      "spectrier",
      "calyrex",
      "meowth-gmax",
      "pikachu-gmax",
      "charizard-gmax",
      "butterfree-gmax",
      "machamp-gmax",
      "gengar-gmax",
      "kingler-gmax",
      "lapras-gmax",
      "eevee-gmax",
      "snorlax-gmax",
      "garbodor-gmax",
      "rillaboom-gmax",
      "cinderace-gmax",
      "inteleon-gmax",
      "corviknight-gmax",
      "orbeetle-gmax",
      "drednaw-gmax",
      "coalossal-gmax",
      "flapple-gmax",
      "appletun-gmax",
      "sandaconda-gmax",
      "toxtricity-gmax",
      "centiskorch-gmax",
      "hatterene-gmax",
      "grimmsnarl-gmax",
      "alcremie-gmax",
      "copperajah-gmax",
      "duraludon-gmax",
      "urshifu-gmax",
      "urshifu-rapid-strike-gmax",
      "toxtricity-low-key",
      "cramorant-gulping",
      "cramorant-gorging",
      "eiscue-noice",
      "morpeko-hangry",
      "zacian-crowned",
      "zamazenta-crowned",
      "eternatus-eternamax",
      "urshifu-rapid-strike",
      "calyrex-ice",
      "calyrex-shadow",

      // Gen 9
      "sprigatito",
      "floragato",
      "meowscarada",
      "fuecoco",
      "crocalor",
      "skeledirge",
      "quaxly",
      "quaxwell",
      "quaquaval",
      "lechonk",
      "oinkologne",
      "tarountula",
      "spidops",
      "nymble",
      "lokix",
      "pawmi",
      "pawmo",
      "pawmot",
      "tandemaus",
      "maushold",
      "fidough",
      "dachsbun",
      "smoliv",
      "dolliv",
      "arboliva",
      "squawkabilly",
      "nacli",
      "naclstack",
      "garganacl",
      "charcadet",
      "armarouge",
      "ceruledge",
      "tadbulb",
      "bellibolt",
      "wattrel",
      "kilowattrel",
      "maschiff",
      "mabosstiff",
      "shroodle",
      "grafaiai",
      "bramblin",
      "brambleghast",
      "toedscool",
      "toedscruel",
      "klawf",
      "capsakid",
      "scovillain",
      "rellor",
      "rabsca",
      "flittle",
      "espathra",
      "tinkatink",
      "tinkaton",
      "wiglett",
      "wugtrio",
      "bombirdier",
      "finizen",
      "palafin",
      "varoom",
      "revavroom",
      "cyclizar",
      "orthworm",
      "glimmet",
      "glimmora",
      "greavard",
      "houndstone",
      "flamigo",
      "cetoddle",
      "cetitan",
      "veluza",
      "dondozo",
      "tatsugiri",
      "annihilape",
      "clodsire",
      "farigiraf",
      "dudunsparce",
      "kingambit",
      "great-tusk",
      "scream-tail",
      "brute-bonnet",
      "flutter-mane",
      "slither-wing",
      "sandy-shocks",
      "iron-treads",
      "iron-bundle",
      "iron-hands",
      "iron-jugulis",
      "iron-moth",
      "iron-thorns",
      "frigibax",
      "arctibax",
      "baxcalibur",
      "gimmighoul",
      "gholdengo",
      "wo-chien",
      "chien-pao",
      "ting-lu",
      "chi-yu",
      "roaring-moon",
      "iron-valiant",
      "koraidon",
      "miraidon",
      "walking-wake",
      "iron-leaves",
      "dipplin",
      "poltchageist",
      "sinistcha",
      "okidogi",
      "munkidori",
      "fezandipiti",
      "ogerpon",
      "archaludon",
      "hydrapple",
      "gouging-fire",
      "raging-bolt",
      "iron-boulder",
      "iron-crown",
      "terapagos",
      "pecharunt",
      "oinkologne-f",
      "maushold-four",
      "squawkabilly-blue",
      "squawkabilly-yellow",
      "squawkabilly-white",
      "tauros-paldea-combat",
      "tauros-paldea-blaze",
      "tauros-paldea-aqua",
      "wooper-paldea",
      "qwilfish-hisui",
      "sneasel-hisui",
    ],
    [],
  )

  useEffect(() => {
    loadPopularPokemon()
  }, [])

  const loadPopularPokemon = async () => {
    setLoading(true)
    try {
      // Load a good selection of popular Pokemon initially
      const popularSelection = pokemonDatabase.slice(0, 100) // First 100 Pokemon for initial load

      const pokemonPromises = popularSelection.map(async (name) => {
        try {
          const pokemon = await fetchPokemon(name)
          return pokemon
        } catch (error) {
          console.error(`Error loading ${name}:`, error)
          return null
        }
      })

      const results = await Promise.all(pokemonPromises)
      setAllPokemon(results.filter(Boolean))
    } catch (error) {
      console.error("Error loading popular Pokemon:", error)
    } finally {
      setLoading(false)
    }
  }

  const fetchPokemon = async (query: string) => {
    try {
      const response = await fetch(`https://pokeapi.co/api/v2/pokemon/${query.toLowerCase()}`)
      if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`)
      const pokemonData = await response.json()

      const speciesResponse = await fetch(pokemonData.species.url)
      if (!speciesResponse.ok) throw new Error(`HTTP error! status: ${speciesResponse.status}`)
      const speciesData = await speciesResponse.json()

      return {
        ...pokemonData,
        species: speciesData,
      }
    } catch (error) {
      console.error(`Error fetching Pokemon ${query}:`, error)
      return null
    }
  }

  // Enhanced search function
  useEffect(() => {
    if (searchTerm.length >= 2) {
      const timeoutId = setTimeout(async () => {
        const term = searchTerm.toLowerCase()

        // First, filter from already loaded Pokemon
        let results = allPokemon.filter(
          (pokemon) => pokemon.name.toLowerCase().includes(term) || pokemon.id.toString().includes(term),
        )

        // If we don't have enough results, search for more Pokemon
        if (results.length < 10) {
          const matchingNames = pokemonDatabase
            .filter((name) => name.toLowerCase().includes(term) && !allPokemon.some((p) => p.name === name))
            .slice(0, 20)

          if (matchingNames.length > 0) {
            const newPokemonPromises = matchingNames.map(async (name) => {
              try {
                return await fetchPokemon(name)
              } catch (error) {
                return null
              }
            })

            const newPokemon = await Promise.all(newPokemonPromises)
            const validNewPokemon = newPokemon.filter(Boolean)

            // Add new Pokemon to our collection
            setAllPokemon((prev) => [...prev, ...validNewPokemon])

            // Update results
            results = [
              ...results,
              ...validNewPokemon.filter(
                (pokemon) => pokemon.name.toLowerCase().includes(term) || pokemon.id.toString().includes(term),
              ),
            ]
          }
        }

        // Also try direct API call if it's a specific name or number
        if (results.length === 0) {
          try {
            const directResult = await fetchPokemon(term)
            if (directResult && !allPokemon.some((p) => p.id === directResult.id)) {
              setAllPokemon((prev) => [directResult, ...prev])
              results = [directResult]
            }
          } catch (error) {
            // Ignore direct search errors
          }
        }

        setSearchResults(results.slice(0, 50))
      }, 300)

      return () => clearTimeout(timeoutId)
    } else {
      setSearchResults([])
    }
  }, [searchTerm, allPokemon, pokemonDatabase])

  // Display Pokemon based on search
  const displayPokemon = useMemo(() => {
    if (!searchTerm || searchTerm.length < 2) {
      return allPokemon.slice(0, 20) // Show first 20 popular Pokemon
    }
    return searchResults
  }, [searchTerm, allPokemon, searchResults])

  const getTypeColor = (type: string) => {
    const colors: { [key: string]: string } = {
      normal: "bg-gray-400",
      fire: "bg-red-500",
      water: "bg-blue-500",
      electric: "bg-yellow-400",
      grass: "bg-green-500",
      ice: "bg-blue-300",
      fighting: "bg-red-700",
      poison: "bg-purple-500",
      ground: "bg-yellow-600",
      flying: "bg-indigo-400",
      psychic: "bg-pink-500",
      bug: "bg-green-400",
      rock: "bg-yellow-800",
      ghost: "bg-purple-700",
      dragon: "bg-indigo-700",
      dark: "bg-gray-800",
      steel: "bg-gray-500",
      fairy: "bg-pink-300",
    }
    return colors[type] || "bg-gray-400"
  }

  const getDisplayName = (name: string) => {
    return name
      .replace("-alola", " (Alolan)")
      .replace("-galar", " (Galarian)")
      .replace("-hisui", " (Hisuian)")
      .replace("-paldea", " (Paldean)")
      .replace("-mega-x", " (Mega X)")
      .replace("-mega-y", " (Mega Y)")
      .replace("-mega", " (Mega)")
      .replace("-gmax", " (Gigantamax)")
      .replace("-", " ")
  }

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <Card className="w-full max-w-3xl max-h-[85vh] overflow-hidden shadow-2xl border-0 bg-gradient-to-br from-white to-gray-50 dark:from-gray-800 dark:to-gray-900">
        <CardHeader className="bg-gradient-to-r from-purple-500 to-pink-500 text-white">
          <div className="flex items-center justify-between">
            <CardTitle className="text-xl font-bold">Choose Your Pokémon</CardTitle>
            <Button variant="ghost" size="icon" onClick={onClose} className="text-white hover:bg-white/20">
              <X className="w-5 h-5" />
            </Button>
          </div>
        </CardHeader>

        <CardContent className="p-6 space-y-4">
          <div className="relative">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-gray-400 w-5 h-5" />
            <Input
              placeholder="Search by name or number (e.g., 'pi', 'char', '25')..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-12 h-12 text-lg rounded-xl border-2 border-purple-200 focus:border-purple-400 bg-white dark:bg-gray-800"
              autoFocus
            />
          </div>

          <ScrollArea className="h-[50vh]">
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <div className="text-center space-y-3">
                  <Loader2 className="w-8 h-8 animate-spin text-purple-500 mx-auto" />
                  <p className="text-gray-600 dark:text-gray-300">Loading Pokémon...</p>
                </div>
              </div>
            ) : displayPokemon.length > 0 ? (
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {displayPokemon.map((pokemon) => (
                  <Card
                    key={pokemon.id}
                    className="cursor-pointer hover:shadow-lg transition-all duration-300 hover:scale-105 border-0 bg-gradient-to-br from-white to-gray-50 dark:from-gray-700 dark:to-gray-800 group"
                    onClick={() => onSelectPokemon(pokemon)}
                  >
                    <CardContent className="p-4">
                      <div className="flex items-center space-x-4">
                        <div className="relative">
                          <div className="w-16 h-16 rounded-full bg-gradient-to-br from-blue-100 to-purple-100 dark:from-blue-900 dark:to-purple-900 p-2 group-hover:from-blue-200 group-hover:to-purple-200 dark:group-hover:from-blue-800 dark:group-hover:to-purple-800 transition-all duration-300">
                            <Image
                              src={
                                pokemon.sprites.other["official-artwork"]?.front_default ||
                                pokemon.sprites.front_default ||
                                "/placeholder.svg?height=64&width=64" ||
                                "/placeholder.svg" ||
                                "/placeholder.svg" ||
                                "/placeholder.svg"
                              }
                              alt={pokemon.name}
                              width={64}
                              height={64}
                              className="object-contain w-full h-full"
                            />
                          </div>
                        </div>
                        <div className="flex-1 min-w-0">
                          <h3 className="font-bold text-lg capitalize truncate group-hover:text-purple-600 dark:group-hover:text-purple-400 transition-colors">
                            {getDisplayName(pokemon.name)}
                          </h3>
                          <p className="text-sm text-gray-500 dark:text-gray-400 mb-2">
                            #{pokemon.id.toString().padStart(3, "0")}
                          </p>
                          <div className="flex flex-wrap gap-1">
                            {pokemon.types.map((type: any) => (
                              <Badge
                                key={type.type.name}
                                className={`${getTypeColor(type.type.name)} text-white text-xs px-2 py-1 rounded-full shadow-sm`}
                              >
                                {type.type.name}
                              </Badge>
                            ))}
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            ) : searchTerm.length >= 2 ? (
              <div className="text-center py-12">
                <div className="text-6xl mb-4">🔍</div>
                <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-2">No Pokémon Found</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  No Pokémon found matching "{searchTerm}". Try a different name or number.
                </p>
              </div>
            ) : (
              <div className="text-center py-8">
                <div className="text-4xl mb-4">⚡</div>
                <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-300 mb-2">Popular Pokémon</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Start typing to search, or choose from these popular Pokémon
                </p>
              </div>
            )}
          </ScrollArea>
        </CardContent>
      </Card>
    </div>
  )
}
